### PR TITLE
SLZB Ember config update

### PR DESCRIPTION
**Pull request by darkxst**
Sync settings to match with ZBDongle-E Settings
* EMBER_APS_UNICAST_MESSAGE_COUNT = 32
* EMBER_PACKET_BUFFER_COUNT = 255

### CODE REVIEW

**Comment by supaeasy** [comment]
Oh will this prevent the error? Where do I put this?

**Comment by darkxst** [comment]
@supaeasy If you are using Ember on Z2M, this will fix those errors at startup. SMLIGHT will be pushing this build out OTA for slzb-06m in the next few hours or you can update directly using the firmware in this PR.

**Comment by darkxst** [comment]
7.4.2 may introduce new issues and needs further testing before pushing out as stable release, however there are builds for 7.4.3(essentially the same as 4.2) here: 
https://github.com/darkxst/silabs-firmware-builder/commits/06M-APS/

**Comment by kalpik** [comment]
Hi,

Just wanted to check how the OTA process works with SMLIGHT. Do they list all of these firmware on OTA? As of now, I only see firmware version 20240408 available as OTA on slzb-06m. Which exact firmware version is this? Is there an option to flash custom zigbee firmware over the network? I know I can flash via USB, but would prefer network.

Thanks

**Comment by darkxst** [comment]
@kalpik 

The version numbers in OTA are different, however `20240510` == 7.4.1 with this ember config updates. You need to install Core firmware 2.2.0.dev before you can install this one though. The actual firmware version will be displayed in logs on startup of Z2M.

You can also flash custom firmware over the network using `universal-silabs-flasher`

```
universal-silabs-flasher --device socket://slzb-06m.local:6638 flash --firmware <file.gbl>
```

**Comment by kalpik** [comment]
Thanks! This explains a lot! But when I try to flash via ethernet, I get this:

`universal-silabs-flasher --device socket://slzb-06m.local:6638 flash --firmware ~\Downloads\ncp-uart-hw-v7.4.2.0-slzb-06m-115200.gbl
2024-05-15 07:47:37.590 U-J956793 universal_silabs_flasher.flash INFO Extracted GBL metadata: NabuCasaMetadata(metadata_version=1, sdk_version='4.4.2', ezsp_version='7.4.2.0', ot_rcp_version=None, cpc_version=None, fw_type=<FirmwareImageType.NCP_UART_HW: 'ncp-uart-hw'>, baudrate=115200)
2024-05-15 07:47:37.590 U-J956793 universal_silabs_flasher.flasher INFO Probing ApplicationType.GECKO_BOOTLOADER at 115200 baud
2024-05-15 07:47:38.593 U-J956793 universal_silabs_flasher.flasher INFO Probing ApplicationType.EZSP at 115200 baud
2024-05-15 07:47:45.739 U-J956793 universal_silabs_flasher.flasher INFO Probing ApplicationType.CPC at 460800 baud
2024-05-15 07:47:46.744 U-J956793 universal_silabs_flasher.flasher INFO Probing ApplicationType.CPC at 115200 baud
2024-05-15 07:47:47.759 U-J956793 universal_silabs_flasher.flasher INFO Probing ApplicationType.CPC at 230400 baud
2024-05-15 07:47:48.769 U-J956793 universal_silabs_flasher.flasher INFO Probing ApplicationType.SPINEL at 460800 baud
Error: Failed to probe running application type`

**Comment by kalpik** [comment]
Never mind. This error was because the z2m container had restarted and connected back to the stick. After shutting down z2m, and then updating, it went fine, thanks!

**Pull request merged**
